# SPDX-License-Identifier: GPL-3.0-only
#
function(id_make_test_home name out_var)
    cmake_parse_arguments(ID_TEST_HOME "" "" "IMAGES;KEYS;PARS" ${ARGN})
    if(ID_TEST_HOME_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown arguments: ${ID_TEST_HOME_UNPARSED_ARGUMENTS}")
    endif()

    set(ID_HOME "${CMAKE_SOURCE_DIR}/home")
    set(home "${CMAKE_CURRENT_BINARY_DIR}/${name}/home")
    file(MAKE_DIRECTORY "${home}")
    file(COPY_FILE "${ID_HOME}/sstools.ini" "${home}/sstools.ini")
    file(COPY_FILE "${ID_HOME}/id.cfg" "${home}/id.cfg")

    if(ID_TEST_HOME_PARS)
        file(MAKE_DIRECTORY "${home}/par")
    endif()
    foreach(par IN LISTS ID_TEST_HOME_PARS)
        get_filename_component(par_name "${par}" NAME)
        if(NOT par STREQUAL par_name)
            message(FATAL_ERROR "PARS entries must be filenames from one parameter library: ${par}")
        endif()
        file(COPY_FILE "${ID_HOME}/par/${par}" "${home}/par/${par}")
    endforeach()

    if(ID_TEST_HOME_KEYS)
        file(MAKE_DIRECTORY "${home}/key")
    endif()
    foreach(key IN LISTS ID_TEST_HOME_KEYS)
        get_filename_component(key_name "${key}" NAME)
        if(NOT key STREQUAL key_name)
            message(FATAL_ERROR "KEYS entries must be filenames from the test directory: ${key}")
        endif()
        file(COPY_FILE "${CMAKE_CURRENT_SOURCE_DIR}/${key}" "${home}/key/${key}")
    endforeach()

    if(ID_TEST_HOME_IMAGES)
        file(MAKE_DIRECTORY "${home}/image")
    endif()
    foreach(image IN LISTS ID_TEST_HOME_IMAGES)
        if(image MATCHES "^([^=]+)=([^=]+)$")
            set(image_source "${CMAKE_MATCH_1}")
            set(image_dest "${CMAKE_MATCH_2}")
        else()
            set(image_source "${image}")
            get_filename_component(image_dest "${image}" NAME)
        endif()
        get_filename_component(image_source_name "${image_source}" NAME)
        if(NOT image_source STREQUAL image_source_name)
            message(FATAL_ERROR "IMAGES entries must be filenames from the image tests: ${image_source}")
        endif()
        get_filename_component(image_dest_name "${image_dest}" NAME)
        if(NOT image_dest STREQUAL image_dest_name)
            message(FATAL_ERROR "IMAGES destination entries must be filenames: ${image_dest}")
        endif()
        file(COPY_FILE "${CMAKE_SOURCE_DIR}/tests/images/${image_source}" "${home}/image/${image_dest}")
    endforeach()

    set(${out_var} "${home}" PARENT_SCOPE)
endfunction()
