
/* fractal image stuff */

#define     IDM_SIZE1	 151
#define     IDM_SIZE2	 152
#define     IDM_SIZE3	 153
#define     IDM_SIZE4	 154
#define     IDM_ITER1	 161
#define     IDM_ITER2	 162
#define     IDM_ITER3	 163

/* fractal formula stuff */

#define     ID_FRACNAME    200
#define     ID_FRACPARAM1  201
#define     ID_FRACPARAM2  202
#define     ID_FRACPARAM3  203
#define     ID_FRACPARAM4  204
#define     ID_FRACPARAM5  205
#define     ID_FRACPARAM6  206
#define     ID_FRACPARTX1  207
#define     ID_FRACPARTX2  208
#define     ID_FRACPARTX3  209
#define     ID_FRACPARTX4  210
#define     ID_FRACPARTX5  211
#define     ID_FRACPARTX6  212
#define     ID_BAILOUT     220
#define     ID_FRACXMIN    221
#define     ID_FRACXMAX    222
#define     ID_FRACYMIN    223
#define     ID_FRACYMAX    224

/* window sizing stuff */

#define     ID_ISIZE	   250
#define     ID_ISIZE1	   251
#define     ID_ISIZE2	   252
#define     ID_ISIZE3	   253
#define     ID_ISIZE4	   254
#define     ID_ISIZE5	   255
#define     ID_ISIZE6	   256
#define     ID_ISIZE7	   257
#define     ID_ISIZE8	   258
#define     ID_ISIZEX	   259
#define     ID_ISIZEY	   260
#define     ID_ICOLORS	   270
#define     ID_ICOLORS1    271
#define     ID_ICOLORS2    272
#define     ID_ICOLORS3    273

/* options and doodads menu */

#define     ID_DEBUGFLAG   290

#define     ID_PASS	   300
#define     ID_PASS1	   301
#define     ID_PASS2	   302
#define     ID_PASSG	   303
#define     ID_PASSB	   304
#define     ID_PASST	   305
#define     ID_PASSD	   306
#define     ID_PASSO	   307

#define     ID_MATHF	   310

#define     ID_MAXIT	   320

#define     ID_BIOMORPH    330

#define     ID_DECOMP	   340

#define     ID_INSIDE	   345
#define     ID_INSIDE2	   356

#define     ID_INSIDEC     346
#define     ID_INSIDEM     347
#define     ID_INSIDEZ     348
#define     ID_INSIDE60    349
#define     ID_INSIDE61    350
#define     ID_INSIDEE     351
#define     ID_INSIDES     352
#define     ID_INSIDEPER   353
#define     ID_INSIDEAT    354
#define     ID_INSIDEFM    355

#define     ID_OUTSIDE	   360
#define     ID_OUTSIDE2	   370

#define     ID_OUTSIDEN    361
#define     ID_OUTSIDEIT   362
#define     ID_OUTSIDER    363
#define     ID_OUTSIDEIM   364
#define     ID_OUTSIDEM    365
#define     ID_OUTSIDES    366
#define     ID_OUTSIDEAT   367
#define     ID_OUTSIDEFM   368
#define     ID_OUTSIDETD   369

#define     ID_FILL        380
#define     ID_FILLC       381

#define     ID_LOGP        390

/* extended options and doodads menu */

#define     ID_FINITE	   300

#define     ID_POTENTMAX   310
#define     ID_POTENTSLOPE 311
#define     ID_POTENTBAIL  312
#define     ID_POTENT16    313

#define     ID_DISTEST     320
#define     ID_DISTESTWID  321

#define     ID_INVERTRAD   330
#define     ID_INVERTX     331
#define     ID_INVERTY     332

#define     ID_COLORMIN    340
#define     ID_COLORMAX    341

#define     ID_NUMSTARS   350
#define     ID_CLUMPINESS 351
#define     ID_DIMRATIO   352

/* Parameter (Batch) Save stuff */

#define     ID_PFILE       210
#define     ID_PENTRY      211
#define     ID_PCOM1       212
#define     ID_PCOM2       213
#define     ID_PCOL1       221
#define     ID_PCOL2       222
#define     ID_PCOL3       223
#define     ID_PCFILE      231
#define     ID_PCNUM       232

/* Color-Cycling stuff */

#define     ID_CYCLEOFF    330
#define     ID_CYCLEON	   331
#define     ID_CYCLEOUT    332
#define     ID_CYCLEIN	   333
#define     ID_CYCLESTAT   334
#define     ID_CYCLECHG    335
#define     ID_CYCLELOW    336
#define     ID_CYCLEMED    337
#define     ID_CYCLEHIGH   338

/* 3D stuff */
#define     ID_PREVIEW	   201
#define     ID_SHOWBOX	   202
#define     ID_SPHERICAL   203
#define     ID_PREVIEWFACTOR 204
#define     ID_STEREO1	   241
#define     ID_STEREO2	   242
#define     ID_STEREO3	   243
#define     ID_STEREO4	   244
#define     ID_FILL1	   211
#define     ID_FILL2	   212
#define     ID_FILL3	   213
#define     ID_FILL4	   214
#define     ID_FILL5	   215
#define     ID_FILL6	   216
#define     ID_FILL7	   217
#define     ID_FILL8	   218
#define     ID_RAY0        220
#define     ID_RAY1        221
#define     ID_RAY2        222
#define     ID_RAY3        223
#define     ID_RAY4        224
#define     ID_RAY5        225
#define     ID_RAY6        226
#define     ID_RAYB        227
#define     ID_RAYN        228
#define     ID_TARGA       231

#define     ID_ANS1	   201
#define     ID_ANS2	   202
#define     ID_ANS3	   203
#define     ID_ANS4	   204
#define     ID_ANS5	   205
#define     ID_ANS6	   206
#define     ID_ANS7	   207
#define     ID_ANS8	   208
#define     ID_ANS9	   209
#define     ID_ANS10	   210
#define     ID_ANS11	   211
#define     ID_ANS12	   212
#define     ID_ANS13	   213
#define     ID_ANS14	   214
#define     ID_ANS15	   215

/* generic fullscreen stuff */

#define     ID_PROMPT00    300
#define     ID_PROMPT01    301
#define     ID_PROMPT02    302
#define     ID_PROMPT03    303
#define     ID_PROMPT04    304
#define     ID_PROMPT05    305
#define     ID_PROMPT06    306
#define     ID_PROMPT07    307
#define     ID_PROMPT08    308
#define     ID_PROMPT09    309
#define     ID_PROMPT10    310
#define     ID_PROMPT11    311
#define     ID_PROMPT12    312
#define     ID_PROMPT13    313
#define     ID_PROMPT14    314
#define     ID_PROMPT15    315
#define     ID_PROMPT16    316
#define     ID_PROMPT17    317
#define     ID_PROMPT18    318
#define     ID_PROMPT19    319
#define     ID_ANSWER01    321
#define     ID_ANSWER02    322
#define     ID_ANSWER03    323
#define     ID_ANSWER04    324
#define     ID_ANSWER05    325
#define     ID_ANSWER06    326
#define     ID_ANSWER07    327
#define     ID_ANSWER08    328
#define     ID_ANSWER09    329
#define     ID_ANSWER10    330
#define     ID_ANSWER11    331
#define     ID_ANSWER12    332
#define     ID_ANSWER13    333
#define     ID_ANSWER14    334
#define     ID_ANSWER15    335
#define     ID_ANSWER16    336
#define     ID_ANSWER17    337
#define     ID_ANSWER18    338
#define     ID_ANSWER19    339


/* status box */

#define     IDS_LINE1	  341
#define     IDS_LINE2	  342
#define     IDS_LINE3	  343
#define     IDS_LINE4	  344
#define     IDS_LINE5	  345
#define     IDS_LINE6	  346
#define     IDS_LINE7	  347
#define     IDS_LINE8	  348
#define     IDS_LINE9	  349
