var searchData=
[
  ['param_5fnot_5fused_2ecpp_0',['param_not_used.cpp',['../d8/dca/param__not__used_8cpp.html',1,'']]],
  ['param_5fnot_5fused_2eh_1',['param_not_used.h',['../d1/d49/param__not__used_8h.html',1,'']]],
  ['parser_2ecpp_2',['parser.cpp',['../dc/ddd/parser_8cpp.html',1,'']]],
  ['parser_2eh_3',['parser.h',['../d5/d36/parser_8h.html',1,'']]],
  ['passes_5foptions_2ecpp_4',['passes_options.cpp',['../dd/dc1/passes__options_8cpp.html',1,'']]],
  ['passes_5foptions_2eh_5',['passes_options.h',['../df/d90/passes__options_8h.html',1,'']]],
  ['path_5fmatch_2ecpp_6',['path_match.cpp',['../d6/dbe/path__match_8cpp.html',1,'']]],
  ['path_5fmatch_2eh_7',['path_match.h',['../d8/de3/path__match_8h.html',1,'']]],
  ['pertengine_2ecpp_8',['PertEngine.cpp',['../dc/d6a/PertEngine_8cpp.html',1,'']]],
  ['pertengine_2eh_9',['PertEngine.h',['../d1/dd3/PertEngine_8h.html',1,'']]],
  ['perturbation_2ecpp_10',['perturbation.cpp',['../d6/da8/perturbation_8cpp.html',1,'']]],
  ['peterson_5fvariations_2ecpp_11',['peterson_variations.cpp',['../d0/ddf/peterson__variations_8cpp.html',1,'']]],
  ['peterson_5fvariations_2eh_12',['peterson_variations.h',['../d8/d6f/peterson__variations_8h.html',1,'']]],
  ['phoenix_2ecpp_13',['phoenix.cpp',['../d6/d4d/phoenix_8cpp.html',1,'']]],
  ['phoenix_2eh_14',['phoenix.h',['../d5/df8/phoenix_8h.html',1,'']]],
  ['pickover_5fmandelbrot_2ecpp_15',['pickover_mandelbrot.cpp',['../d9/d8b/pickover__mandelbrot_8cpp.html',1,'']]],
  ['pickover_5fmandelbrot_2eh_16',['pickover_mandelbrot.h',['../d0/d66/pickover__mandelbrot_8h.html',1,'']]],
  ['pixel_5fgrid_2ecpp_17',['pixel_grid.cpp',['../d9/d35/pixel__grid_8cpp.html',1,'']]],
  ['pixel_5fgrid_2eh_18',['pixel_grid.h',['../d4/d69/pixel__grid_8h.html',1,'']]],
  ['pixel_5flimits_2eh_19',['pixel_limits.h',['../d4/d5b/pixel__limits_8h.html',1,'']]],
  ['plasma_2ecpp_20',['plasma.cpp',['../dd/d9e/Plasma_8cpp.html',1,'(Global Namespace)'],['../d2/da5/plasma_8cpp.html',1,'(Global Namespace)']]],
  ['plasma_2eh_21',['plasma.h',['../d1/d13/Plasma_8h.html',1,'(Global Namespace)'],['../dc/d2b/plasma_8h.html',1,'(Global Namespace)']]],
  ['plot_2ecpp_22',['Plot.cpp',['../da/d2d/Plot_8cpp.html',1,'']]],
  ['plot_2eh_23',['Plot.h',['../d3/d69/Plot_8h.html',1,'']]],
  ['plot3d_2ecpp_24',['plot3d.cpp',['../d3/d14/plot3d_8cpp.html',1,'']]],
  ['plot3d_2eh_25',['plot3d.h',['../d4/d81/plot3d_8h.html',1,'']]],
  ['point_2eh_26',['point.h',['../d8/dc0/math_2Point_8h.html',1,'(Global Namespace)'],['../df/d24/engine_2Point_8h.html',1,'(Global Namespace)']]],
  ['popcorn_2ecpp_27',['popcorn.cpp',['../da/d89/ui_2popcorn_8cpp.html',1,'(Global Namespace)'],['../db/da8/fractals_2popcorn_8cpp.html',1,'(Global Namespace)']]],
  ['popcorn_2eh_28',['popcorn.h',['../d3/d0e/fractals_2popcorn_8h.html',1,'(Global Namespace)'],['../dd/daf/ui_2popcorn_8h.html',1,'(Global Namespace)']]],
  ['population_2ecpp_29',['population.cpp',['../d7/d4a/population_8cpp.html',1,'']]],
  ['population_2eh_30',['population.h',['../d2/d76/population_8h.html',1,'']]],
  ['potential_2ecpp_31',['Potential.cpp',['../d4/db1/Potential_8cpp.html',1,'']]],
  ['potential_2eh_32',['Potential.h',['../d8/d4c/Potential_8h.html',1,'']]],
  ['put_5fstring_5fcenter_2ecpp_33',['put_string_center.cpp',['../d9/d52/put__string__center_8cpp.html',1,'']]],
  ['put_5fstring_5fcenter_2eh_34',['put_string_center.h',['../da/d8d/put__string__center_8h.html',1,'']]]
];
