# SPDX-License-Identifier: GPL-3.0-only
#
set(ID_TEST_DATA_DIR        "${CMAKE_CURRENT_BINARY_DIR}/test_data")
set(ID_TEST_HOME_DIR        "${ID_TEST_DATA_DIR}/home")
set(ID_TEST_SAVE_DIR        "${ID_TEST_DATA_DIR}/save")
set(ID_TEST_FRM_SUBDIR      "formula")
set(ID_TEST_FRM_DIR         "${ID_TEST_HOME_DIR}/${ID_TEST_FRM_SUBDIR}")
set(ID_TEST_IFS_DIR         "${ID_TEST_HOME_DIR}/ifs")
set(ID_TEST_LSYSTEM_SUBDIR  "lsystem")
set(ID_TEST_LSYSTEM_DIR     "${ID_TEST_HOME_DIR}/${ID_TEST_LSYSTEM_SUBDIR}")
set(ID_TEST_MAP_SUBDIR      "map")
set(ID_TEST_MAP_DIR         "${ID_TEST_HOME_DIR}/${ID_TEST_MAP_SUBDIR}")
set(ID_TEST_PAR_SUBDIR      "par")
set(ID_TEST_PAR_DIR         "${ID_TEST_HOME_DIR}/${ID_TEST_PAR_SUBDIR}")

# id.cfg test data
set(ID_TEST_GDI_FN "F6")
set(ID_TEST_GDI_FN_KEY "ID_KEY_F6")
set(ID_TEST_GDI_WIDTH 800)
set(ID_TEST_GDI_HEIGHT 600)
set(ID_TEST_GDI_COLORS 256)
set(ID_TEST_GDI_COMMENT "fancy GDI mode")
set(ID_TEST_GDI_DRIVER "gdi")

set(ID_TEST_DISK_FN "SF8")
set(ID_TEST_DISK_FN_KEY "ID_KEY_SHF_F8")
set(ID_TEST_DISK_WIDTH 1024)
set(ID_TEST_DISK_HEIGHT 768)
set(ID_TEST_DISK_COLORS 256)
set(ID_TEST_DISK_COMMENT "fancier disk mode")
set(ID_TEST_DISK_DRIVER "disk")

set(ID_TEST_SAVE_GDI_FN "SF6")
set(ID_TEST_SAVE_GDI_FN_KEY "ID_KEY_SHF_F6")
set(ID_TEST_SAVE_GDI_WIDTH 1600)
set(ID_TEST_SAVE_GDI_HEIGHT 1200)
set(ID_TEST_SAVE_GDI_COLORS 256)
set(ID_TEST_SAVE_GDI_COMMENT "saved GDI mode")
set(ID_TEST_SAVE_GDI_DRIVER "gdi")

set(ID_TEST_INI "test.ini")
set(ID_TEST_HOME_TOOLS_INI "${ID_TEST_HOME_DIR}/${ID_TEST_INI}")
configure_file("home/test.ini.in" "${ID_TEST_HOME_TOOLS_INI}" @ONLY)

set(ID_TEST_CFG "test.cfg")
set(ID_TEST_HOME_CONFIG_FILE "${ID_TEST_HOME_DIR}/${ID_TEST_CFG}")
set(ID_TEST_SAVE_CONFIG_FILE "${ID_TEST_SAVE_DIR}/${ID_TEST_CFG}")
configure_file("home/test.cfg.in" "${ID_TEST_HOME_CONFIG_FILE}" @ONLY)
configure_file("home/save.cfg.in" "${ID_TEST_SAVE_CONFIG_FILE}" @ONLY)
configure_file("include/test_config_data.h.in" "include/test_config_data.h" @ONLY)

# GIF file extensions test data
set(ID_TEST_GIF_DIR "${ID_TEST_DATA_DIR}/gif")
macro(configure_gif_extension_file num)
    set("EXT${num}_FILE" "extension${num}.gif")
    set("ID_TEST_GIF_EXT${num}_FILE" "${ID_TEST_GIF_DIR}/${EXT${num}_FILE}")
    configure_file("gif/${EXT${num}_FILE}" "${ID_TEST_GIF_EXT${num}_FILE}" COPYONLY)
    set("ID_TEST_GIF_WRITE${num}_FILE" "${ID_TEST_GIF_DIR}/output${num}.gif")
endmacro()
configure_gif_extension_file(1)
configure_gif_extension_file(2)
configure_gif_extension_file(3)
configure_gif_extension_file(4)
configure_gif_extension_file(5)
configure_gif_extension_file(6)
configure_gif_extension_file(7)

function(configure_migrate_int_gif name)
    set(var "ID_TEST_GIF_${name}_INT")
    string(TOUPPER "${var}" var)
    set(path "${ID_TEST_GIF_DIR}/${name}-int.gif")
    configure_file("gif/${name}-int.gif" "${path}" COPYONLY)
    set(${var} "${path}" PARENT_SCOPE)
endfunction()
foreach(name
        mandel julia lambda manowar sierpinski barnsleym1 barnsleyj1
        barnsleym2 barnsleyj2 barnsleym3 barnsleyj3 sqrtrig fnplusfn
        mandellambda marksmandel marksjulia unity mandel4 julia4 trigsqr
        fntimesfn sqr1fn fnmulzz kam kam3d lambdafn manfnzsqrd julfnzsqrd
        mandelfn manzpower julzpower manfnplusexp julfnplusexp popcorn
        lorenz newton newtbasin lorenz3d formula julibrot rossler henon
        spider bifurcation biflambda popcornjulia manowarjulia fnzfnpix
        marksmandelpower timserror bifeqsinpi bifplussinpi bifstewart
        lambdafnfn juliafnfn manlamfnfn mandelfnfn bifmay halleymp
        juliainverse phoenix mandphoenix frothybasin phoenixcmplx
        mandphoenixcmplx
    )
    configure_migrate_int_gif(${name})
endforeach()
configure_file("include/test_migrate_gif.h.in" "include/test_migrate_gif.h" @ONLY)

# IFS test data
set(ID_TEST_FIRST_IFS_NAME      "binary")
set(ID_TEST_FIRST_IFS_PARAM1    ".5")
set(ID_TEST_SECOND_IFS_NAME     "3dfern")
set(ID_TEST_IFS_FILE            "test.ifs")
configure_file("home/test.ifs.in" "${ID_TEST_DATA_DIR}/${ID_TEST_IFS_FILE}")

set(ID_TEST_DATA_SUBDIR_NAME    "subdir")
set(ID_TEST_DATA_SUBDIR         "${ID_TEST_DATA_DIR}/${ID_TEST_DATA_SUBDIR_NAME}")
set(ID_TEST_IFS_FILE2           "test2.ifs")
configure_file("home/test.ifs.in" "${ID_TEST_DATA_SUBDIR}/${ID_TEST_IFS_FILE2}")

# find_file test data
set(ID_TEST_FIND_FILE_SUBDIR            "test_data/find_file")
set(ID_TEST_FIND_FILE_CASEDIR           "casedir")
set(ID_TEST_DATA_FIND_FILE_DIR          "${CMAKE_CURRENT_BINARY_DIR}/${ID_TEST_FIND_FILE_SUBDIR}")
set(ID_TEST_FIND_FILE1                  "find_file1.txt")
set(ID_TEST_FIND_FILE2                  "find_file2.txt")
set(ID_TEST_FIND_FILE3                  "find_file3.txt")
set(ID_TEST_FIND_FILE_CASE_FILENAME     "FIND_FILE4")
set(ID_TEST_FIND_FILE_CASE              "${ID_TEST_FIND_FILE_CASE_FILENAME}.TXT")
configure_file("io/test_find_file.txt.in" "${ID_TEST_FIND_FILE_SUBDIR}/${ID_TEST_FIND_FILE1}")
configure_file("io/test_find_file.txt.in" "${ID_TEST_FIND_FILE_SUBDIR}/${ID_TEST_FIND_FILE2}")
configure_file("io/test_find_file.txt.in" "${ID_TEST_FIND_FILE_SUBDIR}/${ID_TEST_DATA_SUBDIR_NAME}/${ID_TEST_FIND_FILE3}")
configure_file("io/test_find_file.txt.in" "${ID_TEST_FIND_FILE_SUBDIR}/${ID_TEST_FIND_FILE_CASEDIR}/${ID_TEST_FIND_FILE_CASE}")

# check_writefile test data
set(ID_TEST_CHECK_WRITE_FILE_DATA_DIR   "${ID_TEST_DATA_DIR}/check_writefile")
set(ID_TEST_CHECK_WRITE_FILE_NEW        "${ID_TEST_CHECK_WRITE_FILE_DATA_DIR}/new_file.gif")
set(ID_TEST_CHECK_WRITE_FILE_BASE1      "${ID_TEST_CHECK_WRITE_FILE_DATA_DIR}/fract001")
set(ID_TEST_CHECK_WRITE_FILE_EXT        ".gif")
set(ID_TEST_CHECK_WRITE_FILE_OTHER_EXT  ".foo")
set(ID_TEST_CHECK_WRITE_FILE_EXISTS1    "${ID_TEST_CHECK_WRITE_FILE_DATA_DIR}/fract001.gif")
set(ID_TEST_CHECK_WRITE_FILE_EXISTS2    "${ID_TEST_CHECK_WRITE_FILE_DATA_DIR}/fract002.gif")
set(ID_TEST_CHECK_WRITE_FILE3           "${ID_TEST_CHECK_WRITE_FILE_DATA_DIR}/fract003.gif")
configure_file("io/test_check_write_file_data.h.in" "include/test_check_write_file_data.h" @ONLY)
configure_file("gif/extension1.gif"     "${ID_TEST_CHECK_WRITE_FILE_DATA_DIR}/fract001.gif" COPYONLY)
configure_file("gif/extension1.gif"     "${ID_TEST_CHECK_WRITE_FILE_DATA_DIR}/fract002.gif" COPYONLY)
file(REMOVE "${ID_TEST_CHECK_WRITE_FILE_NEW}")
file(REMOVE "${ID_TEST_CHECK_WRITE_FILE3}")

# color map file test data
set(ID_TEST_MAP_FILE "test.map")
configure_file("home/test.map.in" "${ID_TEST_MAP_DIR}/${ID_TEST_MAP_FILE}" @ONLY)

# load_entry_text test data
set(ID_TEST_FRM_FILE "test.frm")
configure_file("home/test.frm.in" "${ID_TEST_FRM_DIR}/${ID_TEST_FRM_FILE}" @ONLY)

set(ID_TEST_IMAGE_FILE              "test.gif")
set(ID_TEST_KEY_FILE                "test.key")
set(ID_TEST_LSYSTEM_FILE            "test.l")
set(ID_TEST_PAR_FILE                "test.par")
configure_file("home/test.ifs.in"   "${ID_TEST_HOME_DIR}/ifs/${ID_TEST_IFS_FILE}")
configure_file("home/test.l.in"     "${ID_TEST_HOME_DIR}/lsystem/${ID_TEST_LSYSTEM_FILE}")
configure_file("home/test.par.in"   "${ID_TEST_HOME_DIR}/par/${ID_TEST_PAR_FILE}")

set(ID_TEST_FORMULA_FILE2           "test2.frm")
set(ID_TEST_IFS_FILE2               "test2.ifs")
set(ID_TEST_IMAGE_FILE2             "test2.gif")
set(ID_TEST_KEY_FILE2               "test2.key")
set(ID_TEST_LSYSTEM_FILE2           "test2.l")
set(ID_TEST_MAP_FILE2               "test2.map")
set(ID_TEST_PAR_FILE2               "test2.par")
set(ID_TEST_LIBRARY_DIR             "${ID_TEST_DATA_DIR}/library")
set(ID_TEST_LIBRARY_DIR1            "${ID_TEST_LIBRARY_DIR}/lib1")
set(ID_TEST_LIBRARY_DIR2            "${ID_TEST_LIBRARY_DIR}/lib2")
set(ID_TEST_LIBRARY_DIR3            "${ID_TEST_LIBRARY_DIR}/lib3")
set(ID_TEST_SEARCH_DIR1             "${ID_TEST_LIBRARY_DIR}/search1")
set(ID_TEST_SEARCH_DIR2             "${ID_TEST_LIBRARY_DIR}/search2")
configure_file("home/test.frm.in"   "${ID_TEST_LIBRARY_DIR}/${ID_TEST_FRM_FILE}" @ONLY)
configure_file("home/test.frm.in"   "${ID_TEST_LIBRARY_DIR1}/root.frm" @ONLY)
configure_file("home/test.ifs.in"   "${ID_TEST_LIBRARY_DIR1}/root.ifs" @ONLY)
configure_file("gif/extension1.gif" "${ID_TEST_LIBRARY_DIR1}/root.gif" COPYONLY)
configure_file("home/test.key.in"   "${ID_TEST_LIBRARY_DIR1}/root.key" @ONLY)
configure_file("home/test.l.in"     "${ID_TEST_LIBRARY_DIR1}/root.l" @ONLY)
configure_file("home/test.map.in"   "${ID_TEST_LIBRARY_DIR1}/root.map" @ONLY)
configure_file("home/test.par.in"   "${ID_TEST_LIBRARY_DIR1}/root.par" @ONLY)
configure_file("home/test.frm.in"   "${ID_TEST_LIBRARY_DIR2}/formula/${ID_TEST_FRM_FILE}" @ONLY)
configure_file("home/test.ifs.in"   "${ID_TEST_LIBRARY_DIR2}/ifs/${ID_TEST_IFS_FILE}" @ONLY)
configure_file("gif/extension1.gif" "${ID_TEST_LIBRARY_DIR2}/image/${ID_TEST_IMAGE_FILE}" COPYONLY)
configure_file("home/test.key.in"   "${ID_TEST_LIBRARY_DIR2}/key/${ID_TEST_KEY_FILE}" @ONLY)
configure_file("home/test.l.in"     "${ID_TEST_LIBRARY_DIR2}/lsystem/${ID_TEST_LSYSTEM_FILE}" @ONLY)
configure_file("home/test.map.in"   "${ID_TEST_LIBRARY_DIR2}/map/${ID_TEST_MAP_FILE}" @ONLY)
configure_file("home/test.par.in"   "${ID_TEST_LIBRARY_DIR2}/par/${ID_TEST_PAR_FILE}" @ONLY)
configure_file("home/test.frm.in"   "${ID_TEST_LIBRARY_DIR3}/formula/root.frm" @ONLY)
configure_file("home/test.ifs.in"   "${ID_TEST_LIBRARY_DIR3}/ifs/root.ifs" @ONLY)
configure_file("gif/extension1.gif" "${ID_TEST_LIBRARY_DIR3}/image/root.gif" COPYONLY)
configure_file("home/test.key.in"   "${ID_TEST_LIBRARY_DIR3}/key/root.key" @ONLY)
configure_file("home/test.l.in"     "${ID_TEST_LIBRARY_DIR3}/lsystem/root.l" @ONLY)
configure_file("home/test.map.in"   "${ID_TEST_LIBRARY_DIR3}/map/root.map" @ONLY)
configure_file("home/test.par.in"   "${ID_TEST_LIBRARY_DIR3}/par/root.par" @ONLY)
configure_file("home/test.frm.in"   "${ID_TEST_SEARCH_DIR1}/root.frm" @ONLY)
configure_file("home/test.frm.in"   "${ID_TEST_SEARCH_DIR1}/formula/${ID_TEST_FRM_FILE}" @ONLY)
configure_file("home/test.ifs.in"   "${ID_TEST_SEARCH_DIR1}/${ID_TEST_IFS_FILE}" @ONLY)
configure_file("home/test.ifs.in"   "${ID_TEST_SEARCH_DIR1}/ifs/${ID_TEST_IFS_FILE}" @ONLY)
configure_file("gif/extension1.gif" "${ID_TEST_SEARCH_DIR1}/image/${ID_TEST_IMAGE_FILE}" COPYONLY)
configure_file("home/test.key.in"   "${ID_TEST_SEARCH_DIR1}/key/${ID_TEST_KEY_FILE}" @ONLY)
configure_file("home/test.l.in"     "${ID_TEST_SEARCH_DIR1}/lsystem/${ID_TEST_LSYSTEM_FILE}" @ONLY)
configure_file("home/test.map.in"   "${ID_TEST_SEARCH_DIR1}/map/${ID_TEST_MAP_FILE}" @ONLY)
configure_file("home/test.par.in"   "${ID_TEST_SEARCH_DIR1}/par/${ID_TEST_PAR_FILE}" @ONLY)
configure_file("home/test.frm.in"   "${ID_TEST_SEARCH_DIR2}/formula/${ID_TEST_FRM_FILE2}" @ONLY)
configure_file("home/test.ifs.in"   "${ID_TEST_SEARCH_DIR2}/ifs/${ID_TEST_IFS_FILE2}" @ONLY)
configure_file("gif/extension1.gif" "${ID_TEST_SEARCH_DIR2}/image/${ID_TEST_IMAGE_FILE2}" COPYONLY)
configure_file("home/test.key.in"   "${ID_TEST_SEARCH_DIR2}/key/${ID_TEST_KEY_FILE2}" @ONLY)
configure_file("home/test.l.in"     "${ID_TEST_SEARCH_DIR2}/lsystem/${ID_TEST_LSYSTEM_FILE2}" @ONLY)
configure_file("home/test.map.in"   "${ID_TEST_SEARCH_DIR2}/map/${ID_TEST_MAP_FILE2}" @ONLY)
configure_file("home/test.par.in"   "${ID_TEST_SEARCH_DIR2}/par/${ID_TEST_PAR_FILE2}" @ONLY)
configure_file("include/test_library.h.in" include/test_library.h @ONLY)

# Test data header
configure_file(include/test_data.h.in include/test_data.h @ONLY)
