TARGET = libMockHardwareLib.a

DOTO =\
  MockFrontPanel.o MockFrontPanelTest.o\
  MockPhoneDialer.o MockPhoneDialerTest.o\


INCLUDE =\
 -I../HomeGuardLib\
 -I../include\
 -I$(CPP_TEST_TOOLS)\
 -I$(CPP_TEST_TOOLS)/Platforms/Gcc\
 -I.

LIBDIR = ../lib

include $(CPP_TEST_TOOLS)/MakefileHelpers/StaticLibMakefile




