TARGET = libMockHardwareLib.a
CPP_PLATFORM = Gcc

DOTO =\
 MockFrontPanel.o

INCLUDE =\
 -I../HomeGuardLib\
 -I../include\
 -I$(CPP_TEST_TOOLS)\
 -I$(CPP_TEST_TOOLS)/Platforms/$(CPP_PLATFORM)\
 -I.

LIBDIR = ../lib

include $(CPP_TEST_TOOLS)/MakefileHelpers/StaticLibMakefile




