TARGET = libHomeGuardLib.a

DOTO =\
 HomeGuard.o HomeGuardTest.o\
 PhoneDialer.o PhoneDialerTest.o\
 FrontPanel.o\

INCLUDE =\
 -I../include\
 -I../MockHardwareLib\
 -I$(CPP_TEST_TOOLS)\
 -I$(CPP_TEST_TOOLS)/Platforms/Gcc\
 -I.

LIBDIR = ../lib

include $(CPP_TEST_TOOLS)/MakefileHelpers/StaticLibMakefile




