TARGET = libHomeGuardLib.a
CPP_PLATFORM = Gcc

DOTO =\
 HomeGuard.o HomeGuardTest.o\
 MockObjectTest.o\

INCLUDE =\
 -I../include\
 -I../MockHardwareLib\
 -I$(CPP_TEST_TOOLS)\
 -I$(CPP_TEST_TOOLS)/Platforms/$(CPP_PLATFORM)\
 -I.

LIBDIR = ../lib

include $(CPP_TEST_TOOLS)/MakefileHelpers/StaticLibMakefile




