TARGET = libUtilLib.a

DOTO =\
 Stack.o StackTest.o\
 Stack.o StackTest.o\
 LogEntry.o LogEntryTest.o\

INCLUDE =\
 -I../include\
 -I../MockHardwareLib\
 -I$(CPP_TEST_TOOLS)\
 -I$(CPP_TEST_TOOLS)/Platforms/$(CPP_PLATFORM)\
 -I.

LIBDIR = ../lib

include $(CPP_TEST_TOOLS)/MakefileHelpers/StaticLibMakefile
