#pragma once

bool MandelSetup();
bool MandelfpSetup();
bool JuliaSetup();
bool StandaloneSetup();
bool UnitySetup();
bool JuliafpSetup();
bool MandellongSetup();
bool JulialongSetup();
bool TrigPlusSqrlongSetup();
bool TrigPlusSqrfpSetup();
bool FnPlusFnSym();
bool JuliafnPlusZsqrdSetup();
bool MandelTrigSetup();
bool SierpinskiSetup();
bool SierpinskiFPSetup();
bool StandardSetup();
bool LambdaTrigOrTrigSetup();
bool JuliaTrigOrTrigSetup();
bool ManlamTrigOrTrigSetup();
bool MandelTrigOrTrigSetup();
bool dynam2dfloatsetup();
