// SPDX-License-Identifier: GPL-3.0-only
//
#pragma once

#include <string>

extern bool                  g_frm_uses_ismand;
extern bool                  g_frm_uses_p1;
extern bool                  g_frm_uses_p2;
extern bool                  g_frm_uses_p3;
extern bool                  g_frm_uses_p4;
extern bool                  g_frm_uses_p5;
extern double                g_fudge_limit;
extern bool                  g_is_mandelbrot;
extern int                   g_last_init_op;
extern int                   g_load_index;
extern char                  g_max_function;
extern unsigned              g_max_function_args;
extern unsigned              g_max_function_ops;
extern unsigned              g_operation_index;
extern int                   g_store_index;
extern unsigned              g_variable_index;

void d_stk_mul();
void l_stk_mul();
void d_stk_abs();
void m_stk_abs();
void l_stk_abs();
void d_stk_sqr();
void m_stk_sqr();
void l_stk_sqr();
void d_stk_conj();
void m_stk_conj();
void l_stk_conj();
void d_stk_zero();
void m_stk_zero();
void l_stk_zero();
void d_stk_one();
void m_stk_one();
void l_stk_one();
void d_stk_flip();
void m_stk_flip();
void l_stk_flip();
void d_stk_sin();
void m_stk_sin();
void l_stk_sin();
void d_stk_tan();
void m_stk_tan();
void l_stk_tan();
void d_stk_tanh();
void m_stk_tanh();
void l_stk_tanh();
void d_stk_cotan();
void m_stk_cotan();
void l_stk_cotan();
void d_stk_cotanh();
void m_stk_cotanh();
void l_stk_cotanh();
void d_stk_recip();
void m_stk_recip();
void l_stk_recip();
void stk_ident();
void d_stk_sinh();
void m_stk_sinh();
void l_stk_sinh();
void d_stk_cos();
void m_stk_cos();
void l_stk_cos();
void d_stk_coxx();
void m_stk_cosxx();
void l_stk_cosxx();
void d_stk_cosh();
void m_stk_cosh();
void l_stk_cosh();
void d_stk_log();
void m_stk_log();
void l_stk_log();
void d_stk_exp();
void m_stk_exp();
void l_stk_exp();
void d_stk_pwr();
void m_stk_pwr();
void l_stk_pwr();
void d_stk_asin();
void m_stk_asin();
void l_stk_asin();
void d_stk_asinh();
void m_stk_asinh();
void l_stk_asinh();
void d_stk_acos();
void m_stk_acos();
void l_stk_acos();
void d_stk_acosh();
void m_stk_acosh();
void l_stk_acosh();
void d_stk_atan();
void m_stk_atan();
void l_stk_atan();
void d_stk_atanh();
void m_stk_atanh();
void l_stk_atanh();
void d_stk_cabs();
void m_stk_cabs();
void l_stk_cabs();
void d_stk_sqrt();
void m_stk_sqrt();
void l_stk_sqrt();
void d_stk_floor();
void m_stk_floor();
void l_stk_floor();
void d_stk_ceil();
void m_stk_ceil();
void l_stk_ceil();
void d_stk_trunc();
void m_stk_trunc();
void l_stk_trunc();
void d_stk_round();
void m_stk_round();
void l_stk_round();
int formula();
int bad_formula();
int form_per_pixel();
int frm_get_param_stuff(char const *Name);
bool run_formula(const std::string &name, bool report_bad_sym);
bool formula_setup_fp();
bool formula_setup_l();
void init_misc();
void free_work_area();
