#pragma once

int LongPhoenixFractal();
int PhoenixFractal();
int long_phoenix_per_pixel();
int phoenix_per_pixel();
int long_mandphoenix_per_pixel();
int mandphoenix_per_pixel();
int LongPhoenixFractalcplx();
int PhoenixFractalcplx();
int LongPhoenixPlusFractal();
int PhoenixPlusFractal();
int LongPhoenixMinusFractal();
int PhoenixMinusFractal();
int LongPhoenixCplxPlusFractal();
int PhoenixCplxPlusFractal();
int LongPhoenixCplxMinusFractal();
int PhoenixCplxMinusFractal();
bool PhoenixSetup();
bool MandPhoenixSetup();
bool PhoenixCplxSetup();
bool MandPhoenixCplxSetup();
