# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright 2026 Richard Thomson
#
# Usage:
#   cmake -DRELEASE_VERSION:STRING=1.4.0 -P scripts/release-notes.cmake
#
# Variables:
#   RELEASE_VERSION Version whose notes should be extracted, with optional
#                   leading v.
#   ID_SOURCE_DIR   Source tree containing hc/src/help.src; defaults to this
#                   script's parent.
#   OUTPUT_FILE     Release notes file to write; defaults to
#                   release-notes-vM.N.P.md under ID_SOURCE_DIR.
#   FOOTER_FILE     Markdown footer to append; defaults to
#                   scripts/release-notes-footer.md under ID_SOURCE_DIR.
#
cmake_minimum_required(VERSION 3.23)

set(ID_RELEASE_BACKSLASH_TOKEN "@@ID_RELEASE_BACKSLASH@@")

function(id_append_line lines_var line)
    set(id_line "${line}")
    string(REPLACE "\\" "${ID_RELEASE_BACKSLASH_TOKEN}" id_line "${id_line}")
    string(REPLACE ";" "\\;" id_line "${id_line}")
    set(lines "${${lines_var}}")
    list(APPEND lines "${id_line}")
    set(${lines_var} "${lines}" PARENT_SCOPE)
endfunction()

function(id_unprotect_line line out_var)
    string(REPLACE "${ID_RELEASE_BACKSLASH_TOKEN}" "\\" result "${line}")
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(id_fail message_text)
    message(FATAL_ERROR "${message_text}")
endfunction()

function(id_require_var name)
    if(NOT DEFINED ${name} OR "${${name}}" STREQUAL "")
        id_fail("${name} must be specified")
    endif()
endfunction()

function(id_parse_version value prefix)
    if(NOT "${value}" MATCHES "^v?([0-9]+)\\.([0-9]+)\\.([0-9]+)(\\.([0-9]+))?$")
        id_fail("Invalid version: ${value}")
    endif()

    set(${prefix}_DISPLAY "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}" PARENT_SCOPE)
    set(${prefix}_TAG "v${CMAKE_MATCH_1}.${CMAKE_MATCH_2}.${CMAKE_MATCH_3}" PARENT_SCOPE)
endfunction()

function(id_read_lines path out_var)
    if(NOT EXISTS "${path}")
        id_fail("Missing file: ${path}")
    endif()

    file(READ "${path}" content)
    set(lines)
    while(TRUE)
        string(FIND "${content}" "\n" newline)
        if(newline EQUAL -1)
            set(line "${content}")
            if(NOT line STREQUAL "")
                string(REGEX REPLACE "\r$" "" line "${line}")
                id_append_line(lines "${line}")
            endif()
            break()
        endif()

        string(SUBSTRING "${content}" 0 ${newline} line)
        math(EXPR next_line "${newline} + 1")
        string(SUBSTRING "${content}" ${next_line} -1 content)
        string(REGEX REPLACE "\r$" "" line "${line}")
        id_append_line(lines "${line}")
    endwhile()
    set(${out_var} "${lines}" PARENT_SCOPE)
endfunction()

function(id_write_lines path lines_var)
    get_filename_component(parent_dir "${path}" DIRECTORY)
    if(NOT parent_dir STREQUAL "")
        file(MAKE_DIRECTORY "${parent_dir}")
    endif()

    file(WRITE "${path}" "")
    foreach(line IN LISTS ${lines_var})
        id_unprotect_line("${line}" line)
        file(APPEND "${path}" "${line}\n")
    endforeach()
endfunction()

function(id_find_line lines_var wanted path out_index)
    set(match_count 0)
    set(match_index -1)
    list(LENGTH ${lines_var} line_count)
    if(line_count GREATER 0)
        math(EXPR last_index "${line_count} - 1")
        foreach(index RANGE 0 ${last_index})
            list(GET ${lines_var} ${index} line)
            id_unprotect_line("${line}" line)
            if(line STREQUAL "${wanted}")
                math(EXPR match_count "${match_count} + 1")
                set(match_index "${index}")
            endif()
        endforeach()
    endif()

    if(NOT match_count EQUAL 1)
        id_fail("${path} must contain exactly one ${wanted} line")
    endif()
    set(${out_index} "${match_index}" PARENT_SCOPE)
endfunction()

function(id_extract_changelog lines_var release_version out_var)
    id_find_line(${lines_var} "; RELEASE CHANGELOG BEGIN" "hc/src/help.src" begin_index)
    id_find_line(${lines_var} "; RELEASE CHANGELOG END" "hc/src/help.src" end_index)
    if(NOT begin_index LESS end_index)
        id_fail("RELEASE CHANGELOG BEGIN must precede RELEASE CHANGELOG END")
    endif()

    set(start_index -1)
    math(EXPR first_index "${begin_index} + 1")
    math(EXPR last_index "${end_index} - 1")
    foreach(index RANGE ${first_index} ${last_index})
        list(GET ${lines_var} ${index} line)
        id_unprotect_line("${line}" line)
        if(line MATCHES "^Version ${release_version}([ .]|$)")
            set(start_index "${index}")
            break()
        endif()
    endforeach()
    if(start_index EQUAL -1)
        id_fail("Could not find Version ${release_version} in changelog")
    endif()

    set(end_index "${last_index}")
    while(end_index GREATER_EQUAL start_index)
        list(GET ${lines_var} ${end_index} line)
        id_unprotect_line("${line}" line)
        if(line STREQUAL "" OR line STREQUAL ";")
            math(EXPR end_index "${end_index} - 1")
        else()
            break()
        endif()
    endwhile()

    set(lines)
    foreach(index RANGE ${start_index} ${end_index})
        list(GET ${lines_var} ${index} line)
        id_unprotect_line("${line}" line)
        id_append_line(lines "${line}")
    endforeach()
    set(${out_var} "${lines}" PARENT_SCOPE)
endfunction()

function(id_markdown_line line release_version out_var)
    string(REGEX REPLACE "\\\\$" "" line "${line}")
    if(line STREQUAL ";")
        set(line "")
    elseif(line STREQUAL "New Features in Version ${release_version}")
        set(line "## New Features")
    elseif(line STREQUAL "Bugs Fixed in Version ${release_version}")
        set(line "## Bugs Fixed")
    elseif(line STREQUAL "Code Cleanup in Version ${release_version}")
        set(line "## Code Cleanup")
    elseif(line STREQUAL "Known limitations:")
        set(line "## Known limitations")
    elseif(line MATCHES "^o (.*)$")
        set(line "- ${CMAKE_MATCH_1}")
    endif()

    set(previous_line "")
    while(NOT line STREQUAL previous_line)
        set(previous_line "${line}")
        string(REGEX REPLACE "\\{\\\"([^{}]*)\\\"\\}" "\\1" line "${line}")
        string(REGEX REPLACE "\\{([^{}]*)\\}" "\\1" line "${line}")
    endwhile()
    set(${out_var} "${line}" PARENT_SCOPE)
endfunction()

function(id_collapse_blank_lines lines_var out_var)
    set(result)
    set(previous_blank TRUE)
    foreach(line IN LISTS ${lines_var})
        id_unprotect_line("${line}" line)
        if(line STREQUAL "")
            if(NOT previous_blank)
                id_append_line(result "")
            endif()
            set(previous_blank TRUE)
        else()
            id_append_line(result "${line}")
            set(previous_blank FALSE)
        endif()
    endforeach()
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(id_markdown_structural line out_var)
    if(line STREQUAL "" OR line MATCHES "^#" OR line MATCHES "^- ")
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(id_join_markdown_lines lines_var out_var)
    set(result)
    foreach(line IN LISTS ${lines_var})
        id_unprotect_line("${line}" line)
        list(LENGTH result result_count)
        if(result_count EQUAL 0)
            id_append_line(result "${line}")
            continue()
        endif()

        math(EXPR previous_index "${result_count} - 1")
        list(GET result ${previous_index} previous_line)
        id_unprotect_line("${previous_line}" previous_line)
        id_markdown_structural("${line}" line_structural)
        id_markdown_structural("${previous_line}" previous_structural)
        if(line_structural OR previous_structural)
            id_append_line(result "${line}")
            continue()
        endif()

        list(REMOVE_AT result ${previous_index})
        id_append_line(result "${previous_line} ${line}")
    endforeach()
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(id_join_markdown_bullets lines_var out_var)
    set(result)
    foreach(line IN LISTS ${lines_var})
        id_unprotect_line("${line}" line)
        list(LENGTH result result_count)
        if(result_count EQUAL 0 OR line STREQUAL "" OR line MATCHES "^#" OR line MATCHES "^- ")
            id_append_line(result "${line}")
            continue()
        endif()

        math(EXPR previous_index "${result_count} - 1")
        list(GET result ${previous_index} previous_line)
        id_unprotect_line("${previous_line}" previous_line)
        if(previous_line MATCHES "^- ")
            list(REMOVE_AT result ${previous_index})
            id_append_line(result "${previous_line} ${line}")
        else()
            id_append_line(result "${line}")
        endif()
    endforeach()
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(id_render_release_notes changelog_var release_version out_var)
    set(lines)
    foreach(line IN LISTS ${changelog_var})
        id_unprotect_line("${line}" line)
        id_markdown_line("${line}" "${release_version}" line)
        id_append_line(lines "${line}")
    endforeach()
    id_join_markdown_bullets(lines lines)
    id_join_markdown_lines(lines lines)
    id_collapse_blank_lines(lines lines)
    set(${out_var} "${lines}" PARENT_SCOPE)
endfunction()

function(id_trim_blank_edges lines_var out_var)
    set(lines "${${lines_var}}")
    while(TRUE)
        list(LENGTH lines line_count)
        if(line_count EQUAL 0)
            break()
        endif()
        list(GET lines 0 line)
        id_unprotect_line("${line}" line)
        if(NOT line STREQUAL "")
            break()
        endif()
        list(REMOVE_AT lines 0)
    endwhile()

    while(TRUE)
        list(LENGTH lines line_count)
        if(line_count EQUAL 0)
            break()
        endif()
        math(EXPR last_index "${line_count} - 1")
        list(GET lines ${last_index} line)
        id_unprotect_line("${line}" line)
        if(NOT line STREQUAL "")
            break()
        endif()
        list(REMOVE_AT lines ${last_index})
    endwhile()

    set(${out_var} "${lines}" PARENT_SCOPE)
endfunction()

function(id_append_footer notes_var footer_path out_var)
    id_read_lines("${footer_path}" footer_lines)
    id_trim_blank_edges(${notes_var} notes)
    id_trim_blank_edges(footer_lines footer)

    set(result "${notes}")
    list(LENGTH footer footer_count)
    if(footer_count GREATER 0)
        id_append_line(result "")
        foreach(line IN LISTS footer)
            id_unprotect_line("${line}" line)
            id_append_line(result "${line}")
        endforeach()
    endif()

    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

id_require_var(RELEASE_VERSION)
id_parse_version("${RELEASE_VERSION}" RELEASE)

if(NOT DEFINED ID_SOURCE_DIR OR "${ID_SOURCE_DIR}" STREQUAL "")
    get_filename_component(ID_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
file(TO_CMAKE_PATH "${ID_SOURCE_DIR}" ID_SOURCE_DIR)

if(NOT DEFINED OUTPUT_FILE OR "${OUTPUT_FILE}" STREQUAL "")
    set(OUTPUT_FILE "${ID_SOURCE_DIR}/release-notes-${RELEASE_TAG}.md")
endif()

if(NOT DEFINED FOOTER_FILE OR "${FOOTER_FILE}" STREQUAL "")
    set(FOOTER_FILE "${ID_SOURCE_DIR}/scripts/release-notes-footer.md")
endif()

id_read_lines("${ID_SOURCE_DIR}/hc/src/help.src" help_src_lines)
id_extract_changelog(help_src_lines "${RELEASE_DISPLAY}" changelog_lines)
id_render_release_notes(changelog_lines "${RELEASE_DISPLAY}" release_note_lines)
id_append_footer(release_note_lines "${FOOTER_FILE}" release_note_lines)
id_write_lines("${OUTPUT_FILE}" release_note_lines)

message(STATUS "Wrote release notes for ${RELEASE_DISPLAY} to ${OUTPUT_FILE}")
