TARGET = libUtilLib.a

DOTO =\
 LogEntry.o LogEntryTest.o\

INCLUDE =\
 -I../include\
 -I../MockHardwareLib\
 -I$(CPP_TEST_TOOLS)\
 -I$(CPP_TEST_TOOLS)/Platforms/Gcc\
 -I.

LIBDIR = ../lib

include $(CPP_TEST_TOOLS)/CppSourceTemplates/StaticLibMakefile




