# SPDX-License-Identifier: GPL-3.0-only
#
name: build

permissions:
  packages: write

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

env:
  FEED_URL: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

jobs:
  #############################################################################
  ascii-doc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Install System Dependencies for building AsciiDoc
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y mono-complete

    - name: Add NuGet sources
      shell: bash
      run: |
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -Source "${{env.FEED_URL}}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{github.repository_owner}}" \
          -Password "${{secrets.GH_PACKAGES_TOKEN}}"
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
          -Source "${{env.FEED_URL}}"

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Run Workflow
      env: 
        VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
      run: |
        cmake --version
        cmake --workflow --preset ci-ascii-doc

    - name: Upload AsciiDoc artifact
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: ascii-doc
        path: ${{github.workspace}}/build-ci-ascii-doc/hc/src/id.adoc

  #############################################################################
  pdf-doc:
    needs: ascii-doc
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683   # v4.2.2
      with:
        submodules: true

    - name: Get AsciiDoc artifact
      uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
      with:
        name: ascii-doc
        path: ${{github.workspace}}/build-ci-ascii-doc/hc/src/

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Setup AsciiDoctor
      uses: reitzig/actions-asciidoctor@c642db5eedd1d729bb8c92034770d0b2f769eda6 # v2.0.2
      with:
        version: 2.0.18

    - name: Install AsciiDoctor PDF
      run: |
        gem install asciidoctor-pdf

    - name: Run AsciiDoctor PDF
      run: |
        asciidoctor-pdf --version
        asciidoctor-pdf build-ci-ascii-doc/hc/src/id.adoc

    - name: Upload PDF artifact
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: pdf-docs
        path: ${{github.workspace}}/build-ci-ascii-doc/hc/src/id.pdf

  #############################################################################
  html-docs:
    needs: ascii-doc
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Get AsciiDoc artifact
      uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
      with:
        name: ascii-doc
        path: ${{github.workspace}}/build-ci-ascii-doc/hc/src/

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Setup AsciiDoctor
      uses: reitzig/actions-asciidoctor@c642db5eedd1d729bb8c92034770d0b2f769eda6 # v2.0.2
      with:
        version: 2.0.18

    - name: Run AsciiDoctor
      run: |
        asciidoctor --version
        asciidoctor build-ci-ascii-doc/hc/src/id.adoc

    - name: Upload HTML artifact
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: html-docs
        path: ${{github.workspace}}/build-ci-ascii-doc/hc/src/id.html

  #############################################################################
  build:
    needs: html-docs
    strategy:
      matrix:
        preset: [ debug, release ]
        # macos-latest is disabled for now
        os: [ windows-latest ]
        include:
          #- os: macos-latest
          #  nuget: mono `./vcpkg/vcpkg fetch nuget | tail -n 1`
          - os: windows-latest
            nuget: nuget

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Install Prerequisites Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y mono-complete

    #- name: Install Prerequisites macOS
    #  if: ${{matrix.os == 'macos-latest'}}
    #  shell: bash
    #  run: |
    #    ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh

    - name: Add NuGet sources
      shell: bash
      run: |
        ${{matrix.nuget}} \
          sources add \
          -Source "${{env.FEED_URL}}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{github.repository_owner}}" \
          -Password "${{secrets.GH_PACKAGES_TOKEN}}"
        ${{matrix.nuget}} \
          setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
          -Source "${{env.FEED_URL}}"

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Get HTML documentation
      uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
      with:
        name: html-docs

    - name: Run Workflow
      env: 
        VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
      run: cmake --workflow --preset ci-${{matrix.preset}}

    - name: Build Setup package
      if: ${{matrix.os == 'windows-latest'}}
      run: cmake --build --preset ci-${{matrix.preset}} --target setup

    - name: Upload setup package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Setup-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*-Setup.exe
        compression-level: 0

    - name: Upload msi package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Msi-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.msi
        compression-level: 0

    - name: Upload zip package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Zip-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.zip
        compression-level: 0

    - name: Upload tar.gz package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'ubuntu-latest'}}
      with:
        name: Tar-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.tar.gz
        compression-level: 0

  #############################################################################
  wx:
    needs: html-docs
    strategy:
      matrix:
        preset: [ wx-debug, wx-release ]
        # macos-latest is disabled for now
        os: [ ubuntu-latest, windows-latest ]
        include:
          #- os: macos-latest
          #  nuget: mono `./vcpkg/vcpkg fetch nuget | tail -n 1`
          - os: ubuntu-latest
            nuget: mono `./vcpkg/vcpkg fetch nuget | tail -n 1`
          - os: windows-latest
            nuget: nuget

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Install Prerequisites Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sed 's/#.*//' ${{github.workspace}}/.github/workflows/wx-requirements.txt | xargs sudo apt-get install 

    #- name: Install Prerequisites macOS
    #  if: ${{matrix.os == 'macos-latest'}}
    #  shell: bash
    #  run: |
    # ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh

    - name: Add NuGet sources
      shell: bash
      run: |
        ${{matrix.nuget}} \
          sources add \
          -Source "${{env.FEED_URL}}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{github.repository_owner}}" \
          -Password "${{secrets.GH_PACKAGES_TOKEN}}"
        ${{matrix.nuget}} \
          setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
          -Source "${{env.FEED_URL}}"

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Get HTML documentation
      uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
      with:
        name: html-docs

    - name: Run Workflow
      env: 
        VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
      run: cmake --workflow --preset ci-${{matrix.preset}}

    - name: Build Setup package
      if: ${{matrix.os == 'windows-latest'}}
      run: cmake --build --preset ci-${{matrix.preset}} --target setup

    - name: Upload setup package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Setup-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*-Setup.exe
        compression-level: 0

    - name: Upload msi package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Msi-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.msi
        compression-level: 0

    - name: Upload zip package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Zip-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.zip
        compression-level: 0

    - name: Upload tar.gz package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'ubuntu-latest'}}
      with:
        name: Tar-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.tar.gz
        compression-level: 0
