# SPDX-License-Identifier: GPL-3.0-only
#
name: CMake

permissions:
  packages: write

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

env:
  FEED_URL: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

jobs:
  #############################################################################
  html-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Install System Dependencies for building HTML docs
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y mono-complete

    - name: Add NuGet sources
      shell: bash
      run: |
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -Source "${{env.FEED_URL}}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{github.repository_owner}}" \
          -Password "${{secrets.GH_PACKAGES_TOKEN}}"
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
          -Source "${{env.FEED_URL}}"

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Run Workflow
      env: 
        VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
      run: |
        cmake --version
        cmake --workflow --preset ci-html-docs

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Setup AsciiDoctor
      uses: reitzig/actions-asciidoctor@c642db5eedd1d729bb8c92034770d0b2f769eda6 # v2.0.2
      with:
        version: 2.0.18

    - name: Run AsciiDoctor
      run: |
        asciidoctor --version
        asciidoctor build-ci-html-docs/hc/src/id.adoc

    - name: Upload HTML artifact
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: html-docs
        path: ${{github.workspace}}/build-ci-html-docs/hc/src/id.html

  #############################################################################
  msvc-static-analysis:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
        with:
          submodules: true

      - name: Add NuGet sources
        shell: bash
        run: |
          nuget \
            sources add \
            -Source "${{env.FEED_URL}}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{github.repository_owner}}" \
            -Password "${{secrets.GH_PACKAGES_TOKEN}}"
          nuget \
            setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
            -Source "${{env.FEED_URL}}"

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
        with:
          cmake-version: '3.31'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Configure CMake for Static Analysis
        env: 
          VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
        run: |
          cmake --version
          cmake --preset ci-debug

      - name: Run Static Analysis
        run: |
          msbuild build-ci-debug/ALL_BUILD.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:EnableClangTidyCodeAnalysis=true /p:RunCodeAnalysis=true /p:CodeAnalysisRuleSet=AllRules.ruleset /p:TreatWarningsAsErrors=false /flp:logfile=static-analysis-report.log;verbosity=diagnostic

      - name: Convert Log to Text Report
        shell: pwsh
        run: |
          $logContent = Get-Content "static-analysis-report.log" -Raw
          $analysisWarnings = $logContent | Select-String -Pattern "warning CA\d+:|warning C\d+:" -AllMatches
          
          $reportContent = @"
          MSVC Static Analysis Report
          Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')
          Repository: ${{github.repository}}
          Commit: ${{github.sha}}
          
          ========================================
          ANALYSIS SUMMARY
          ========================================
          
          "@
          
          if ($analysisWarnings.Count -eq 0) {
              $reportContent += "No static analysis warnings found.`n"
          } else {
              $reportContent += "Total warnings found: $($analysisWarnings.Count)`n`n"
              $reportContent += "========================================`n"
              $reportContent += "DETAILED WARNINGS`n"
              $reportContent += "========================================`n`n"
              
              foreach ($warning in $analysisWarnings) {
                  $reportContent += "$($warning.Line)`n"
              }
          }
          
          $reportContent | Out-File -FilePath "msvc-static-analysis-report.txt" -Encoding UTF8

      - name: Upload Static Analysis Report
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: msvc-static-analysis
          path: |
            msvc-static-analysis-report.txt
            static-analysis-report.log

  #############################################################################
  build:
    needs: html-docs
    strategy:
      matrix:
        preset: [ debug, release ]
        # macos-latest is disabled for now
        os: [ windows-latest ]
        include:
          #- os: macos-latest
          #  nuget: mono `./vcpkg/vcpkg fetch nuget | tail -n 1`
          - os: windows-latest
            nuget: nuget

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Install Prerequisites Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y mono-complete

    #- name: Install Prerequisites macOS
    #  if: ${{matrix.os == 'macos-latest'}}
    #  shell: bash
    #  run: |
    #    ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh

    - name: Add NuGet sources
      shell: bash
      run: |
        ${{matrix.nuget}} \
          sources add \
          -Source "${{env.FEED_URL}}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{github.repository_owner}}" \
          -Password "${{secrets.GH_PACKAGES_TOKEN}}"
        ${{matrix.nuget}} \
          setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
          -Source "${{env.FEED_URL}}"

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Get HTML documentation
      uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
      with:
        name: html-docs

    - name: Run Workflow
      env: 
        VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
      run: cmake --workflow --preset ci-${{matrix.preset}}

    - name: Build Setup package
      if: ${{matrix.os == 'windows-latest'}}
      run: cmake --build --preset ci-${{matrix.preset}} --target setup

    - name: Upload setup package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Setup-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*-Setup.exe
        compression-level: 0

    - name: Upload msi package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Msi-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.msi
        compression-level: 0

    - name: Upload zip package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Zip-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.zip
        compression-level: 0

    - name: Upload tar.gz package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'ubuntu-latest'}}
      with:
        name: Tar-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.tar.gz
        compression-level: 0

  #############################################################################
  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
        with:
          submodules: true

      - name: Install System Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo dpkg-reconfigure man-db
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y mono-complete

      - name: Add NuGet sources
        shell: bash
        run: |
          mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
            sources add \
            -Source "${{env.FEED_URL}}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{github.repository_owner}}" \
            -Password "${{secrets.GH_PACKAGES_TOKEN}}"
          mono `./vcpkg/vcpkg fetch nuget | tail -n 1` \
            setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
            -Source "${{env.FEED_URL}}"

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
        with:
          cmake-version: '3.31'

      - name: Configure Compilation Database
        env: 
          VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
        run: |
          cmake --version
          cmake --preset cppcheck
  
      - name: Run CppCheck
        uses: deep5050/cppcheck-action@b4d7c69b911c24817691b4b210586568a858b4c5 # v3.0
        with:
          github_token: ${{secrets.GH_PACKAGES_TOKEN}}
          enable: 'style'
          force: 'enable'
          other_options: >-
            --library=googletest
            --suppress=commaSeparatedReturn
            --suppress=cstyleCast
            --suppress=functionConst
            --suppress=functionStatic
            --suppress=incorrectStringBooleanError
            --suppress=invalidPointerCast
            --suppress=invalidscanf
            --suppress=variableHidingEnum
            --suppress=variableScope
            --inline-suppr
            -I headers hc common headers unix win32
            -ilegacy
            -ivcpkg
            -i../build-cppcheck/vcpkg_installed

      - name: Print Report
        run: cmake -E cat cppcheck_report.txt

      - name: Upload Report
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: CppCheck
          path: cppcheck_report.txt

  #############################################################################
  gh-pages-cppcheck:
    needs: cppcheck
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
        with:
          ref: gh-pages
          submodules: false

      - name: Clear Directory
        run: rm -rf dev/cppcheck 

      - name: Get Report
        uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
        with:
          name: CppCheck
          path: dev/cppcheck

      - name: Update Contents
        run: |
          git config user.name CppCheck
          git config user.email cppcheck-bot@example.com
          git status
          git add dev/cppcheck
          git status
          git commit -m "Update CppCheck report for ${{github.sha}}" || echo "No changes to commit"
          git status
          git log -n 1

      - name: Push Updates
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa # v1.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: gh-pages
          force: false

  #############################################################################
  gh-pages-msvc-static-analysis:
    needs: msvc-static-analysis
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
        with:
          ref: gh-pages
          submodules: false

      - name: Clear Directory
        run: rm -rf dev/msvc-static-analysis 

      - name: Get Report
        uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
        with:
          name: msvc-static-analysis
          path: dev/msvc-static-analysis

      - name: Update Contents
        run: |
          git config user.name "MSVC Static Analysis"
          git config user.email msvc-static-analysis-bot@example.com
          git status
          git add dev/msvc-static-analysis
          git status
          git commit -m "Update MSVC Static Analysis report for ${{github.sha}}" || echo "No changes to commit"
          git status
          git log -n 1

      - name: Push Updates
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa # v1.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: gh-pages
          force: false

  #############################################################################
  wx:
    needs: html-docs
    strategy:
      matrix:
        preset: [ wx-debug, wx-release ]
        # macos-latest is disabled for now
        os: [ ubuntu-latest, windows-latest ]
        include:
          #- os: macos-latest
          #  nuget: mono `./vcpkg/vcpkg fetch nuget | tail -n 1`
          - os: ubuntu-latest
            nuget: mono `./vcpkg/vcpkg fetch nuget | tail -n 1`
          - os: windows-latest
            nuget: nuget

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Install Prerequisites Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sed 's/#.*//' ${{github.workspace}}/.github/workflows/wx-requirements.txt | xargs sudo apt-get install

    #- name: Install Prerequisites macOS
    #  if: ${{matrix.os == 'macos-latest'}}
    #  shell: bash
    #  run: |
    #    ${{github.workspace}}/vcpkg/bootstrap-vcpkg.sh

    - name: Add NuGet sources
      shell: bash
      run: |
        ${{matrix.nuget}} \
          sources add \
          -Source "${{env.FEED_URL}}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{github.repository_owner}}" \
          -Password "${{secrets.GH_PACKAGES_TOKEN}}"
        ${{matrix.nuget}} \
          setapikey "${{secrets.GH_PACKAGES_TOKEN}}" \
          -Source "${{env.FEED_URL}}"

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Get HTML documentation
      uses: actions/download-artifact@7a1cd3216ca9260cd8022db641d960b1db4d1be4 # v4.0.0
      with:
        name: html-docs

    - name: Run Workflow
      env: 
        VCPKG_BINARY_SOURCES: "clear;nuget,${{env.FEED_URL}},readwrite"
      run: cmake --workflow --preset ci-${{matrix.preset}}

    - name: Build Setup package
      if: ${{matrix.os == 'windows-latest'}}
      run: cmake --build --preset ci-${{matrix.preset}} --target setup

    - name: Upload setup package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Setup-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*-Setup.exe
        compression-level: 0

    - name: Upload msi package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Msi-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.msi
        compression-level: 0

    - name: Upload zip package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'windows-latest'}}
      with:
        name: Zip-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.zip
        compression-level: 0

    - name: Upload tar.gz package artifacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      if: ${{matrix.os == 'ubuntu-latest'}}
      with:
        name: Tar-${{matrix.preset}}
        path: ${{github.workspace}}/build-ci-${{matrix.preset}}/*.tar.gz
        compression-level: 0
