name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        preset: [ debug, release ]
        include:
          - { os: ubuntu-latest, install: install }
          - { os: windows-latest, install: INSTALL }
          # macos-latest is disabled for now

    runs-on: ${{matrix.os}}

    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Set Environment Variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Run Workflow
      run: cmake --workflow --preset ${{matrix.preset}}

    - name: Build install target
      run: cmake --build --preset ${{matrix.preset}} --target ${{matrix.install}} 

  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
         
      - name: Configure Compilation Database
        run: cmake --preset cppcheck
  
      - name: Run CppCheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          enable: 'style'
          force: 'enable'
          other_options: >-
            --suppress=commaSeparatedReturn
            --suppress=cstyleCast
            --suppress=functionStatic
            --suppress=incorrectStringBooleanError
            --suppress=invalidPointerCast
            --suppress=invalidscanf
            --suppress=variableHidingEnum
            --suppress=variableScope
            --inline-suppr
            -I headers hc common headers unix win32
            -ifractint
            -ivcpkg
            -i../build-cppcheck/vcpkg_installed

      - name: Print Report
        run: cmake -E cat cppcheck_report.txt
