name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Set Environment Variables
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Run Workflow
      run: cmake --workflow --preset default

  windows-build:
    runs-on: windows-latest
    
    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Set Environment Variables
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: CMake Workflow
      run: cmake --workflow --preset default

  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: Configure Compilation Database
        run: cmake --preset cppcheck
  
      - name: Run CppCheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          enable: 'style'
          force: 'enable'
          other_options: >-
            --suppress=commaSeparatedReturn
            --suppress=cstyleCast
            --suppress=functionStatic
            --suppress=incorrectStringBooleanError
            --suppress=invalidPointerCast
            --suppress=invalidscanf
            --suppress=variableHidingEnum
            --suppress=variableScope
            --inline-suppr
            -I headers hc common headers unix win32
            -ifractint

      - name: Print Report
        run: cmake -E cat cppcheck_report.txt
