name: CppCheck Analysis
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@v3.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - run: cmake -E cat cppcheck_report.txt
